# common
main = "src/index.ts"
compatibility_date = "2022-09-05"
name = "self-hosted-cdn"


[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "desktop-app-assets"
preview_bucket_name = "desktop-app-assets"

# [[routes]]
# pattern = "your-domain-here"
# custom_domain = true

# TODO: add dev env
